language: python
sudo: false
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
  - "/^\\d\\.\\d+\\.\\d+(rc\\d+|\\.dev\\d+)?$/"
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install:
- |
  if [ "$TOXENV" = "pypy" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
      pushd "$PYENV_ROOT" && git pull && popd
    else
      rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
    fi
    # get latest portable PyPy from pyenv directly (thanks to natural version sort option -V)
    export PYPY_VERSION=`"$PYENV_ROOT/bin/pyenv" install --list |grep -o -E 'pypy-portable-[0-9][\.0-9]*$' |sort -V |tail -1`
    "$PYENV_ROOT/bin/pyenv" install --skip-existing "$PYPY_VERSION"
    virtualenv --python="$PYENV_ROOT/versions/$PYPY_VERSION/bin/python" "$HOME/virtualenvs/$PYPY_VERSION"
    source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
  fi
- pip install -U tox twine wheel codecov
script: tox
after_success:
- codecov
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
    - irc.freenode.org#scrapy
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: xiaowangwindow
  password:
    secure: UF0+ljiCXY2TcHKoZbiGWREXS87wlEG8tgi/pkxClwypI5Dy6VG+qX8kahzjr8p9v5VyvzjHjyxdkAZC5wFwu9KtQahg8l1uXXqLILDl05TDJ0t1xQqSLCqe+a1sTzBGlpHDraULkQO6tbTkc8oawewA+VmpqR+Vdx30QcUXDV3LDcri5VzUFczdkb0VULGOBEB1JNhETAoB2KdhZtwTPKC/2tgubKO0lWCCImxw3mgv3Ym7oUPhqsy2hOuOMc3wDsdk+ehmsX9+bZyKwzDWMrErvgJTALB4wsyiTRJfPzFEXFLurYagU4PkatTVU744xzUBtC2ArP9tXbhHBDtHD6lX5CCE3sLLHpuTAXk52zjgLJCSuIvJjNYmrRiog9FAtxsstFdk18TF/2d6UApTwdp1DT1YLGzG5yuLQSR1DUUjZj8KiwM/bX4BTWayPFK6Uw5Ev07Mu6TV5n1Jt4Ct2zE8xfa/L3TkLrOjrwTnPllq+33REuwq3LzFeJ9EDyXAt8mYaTTHqTvoeZZDsPmcqlE5gS+xDhwAVQABK4HAxIvydfOpJ9Foh0XBOR3+oAqXZ4B7EwOkzas1RG2j6mhtgYFtHkHDGHgbqs1ELYc68b8xLf8cLvuxqSQyBEy//vFvNnPfBJn/VSBFnqVb7XHs2XLF6J1XpDTMQPEU2VPSGhw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: xiaowangwindow/scrapy-httpcache
